#This pubspec file imports is used for any dependencies for standard Dartstream features.
#This works for both mobile and web.
name: ds_standard_features
description: Packages for our standard features - maintained by the Dart team.
version: 0.0.1-pre+11
repository: https://github.com/aortem/dartstream

environment:
 sdk: ">=3.4.0 <4.0.0"

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# STANDARD PACKAGES - Built By The Dart Team
  args: ^2.5.0
  async: ^2.11.0
  build: ^2.4.1
  characters: ^1.3.0
  collection: ^1.18.0
  convert: ^3.1.1
  crypto: ^3.0.3
  ds_custom_middleware: ^0.0.1-pre
  ds_shelf: ^0.0.1-pre+3
  fake_async: ^1.3.1
  fixnum: ^1.1.0
  http: ^1.2.2
  http2: ^2.3.0
  http_parser: ^4.0.2 #Do not update.  Flutter SDK is currently tied to version 1.18 of the package collection
  intl: ^0.19.0
  intl_translation: ^0.20.0
  logging: ^1.2.0
  meta: ^1.11.0
  os_detect: ^2.0.1
  path: ^1.9.0
  typed_data: ^1.3.2
 
#Globally Activated Package
#executables:
#   ds: ds_cli