#This pubspec file imports is used for any dependencies for standard Dartstream features.

name: ds_vue_framework_base
description: Packages for our vue framework - maintained by the Aortem and Dart team.
version: 0.0.1-pre+1
repository: https://github.com/aortem/dartstream

environment:
 sdk: ^3.7.0

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# STANDARD PACKAGES - Built By The Dart Team
  ds_standard_features: ^0.0.1-pre+11