#This pubspec file is used for any dependencies that both the frontend and backend framework use(aka. shared dependencies)
name: ds_tools_general
description: Dartstream General Tools.
version: 0.0.1-pre
repository: https://github.com/dartstream

environment:
 sdk: ">=3.4.0 <4.0.0"

# Dependencies are added in sections alphabetically and according to features.
dependencies:
#Testing Packages
  mime: ^1.0.5

#Globally Activated Package
#executables:
#   ds: ds_cli