#This pubspec file imports is used for any dependencies that both the frontend and backend framework use(aka. shared dependencies)
name: ds_enhanced_features
description: Packages for our enhanced features
version: 0.0.1-pre
# repository: https://github.com/my_org/my_repo

environment:
 sdk: ">=3.3.0 <4.0.0"

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# MIDDLEWARE - USE ONLY ONE

# Shelf Middleware Import  // On By Default
  ds_shelf: ^0.0.1-pre

# Custom Middleware Import // Off By Default

# STANDARD FEATURES
  ds_standard_features: ^0.0.1-pre+5

# ENHANCED FEATURES

# Database
  sqlite3: ^2.4.2 #Local database development - No driver


#Cosmetic
  lints: ^3.0.0 #Included In ds_standard_features


#Globally Activated Package
executables:
   ds: ds_cli