name: ds_dartstream
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  postgres: ^3.0.0 # For PostgreSQL
  aws_signature_v4: ^0.5.0 # For AWS DynamoDB
  http: ^1.1.2

  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
