# This pubspec file is used for any dependencies that both the frontend and backend framework use(aka. shared dependencies)
name: ds_dartstream
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
 sdk: "^3.3.0"

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# Multi Repository Dependencies
  melos: ^5.2.2

# Dev dependencies are added in sections alphabetically and according to features.
dev_dependencies:

# CLI
  cli_util: ^0.4.1
#TBD
  lints: ^2.1.0
  test: ^1.24.0
