#This pubspec file imports is used for any dependencies for standard Dartstream features.

name: ds_flutter_games_framework_base
description: Packages for our Flutter games framework - maintained by the Aortem and Dart team.
version: 0.0.1-pre+1
repository: https://github.com/dartstream

environment:
 sdk: ">=3.4.0 <4.0.0"

# Dependencies are added in sections alphabetically and according to features.
dependencies:

# STANDARD PACKAGES - Built By The Dart Team
  ds_standard_features: ^0.0.1-pre+11