name: firebase_dart_admin_auth_sdk
description: A Dart SDK for Firebase Admin Authentication, enabling secure server-side authentication and user management for Dart-based backend applications.
version: 0.0.2
repository: https://github.com/aortem/firebase-dart-admin-auth-sdk
license: BSD-3

environment:
   sdk: ^3.8.1


# Add regular dependencies here.

dependencies:
#------------------ STANDARD FEATURES---------------------------------
## There are three standard libraries. 

  ds_standard_features: ^0.0.4  # Dart Team Utilities For HTTP //Default
  googleapis_auth: ^2.0.0 #Googe Apis
  jwt_generator: ^0.0.3 # Internal JWT Generator Package
  
#------------------ TESTING FEATURES---------------------------------

dev_dependencies:
  ds_tools_testing: ^0.0.4 #Standard Dart Team Testing Tools
  git_hooks: any

# Optional Local Hooks for development.
git_hooks:
  hooks:
    pre-commit: ./local_dev_tools/validate_commit.dart
    commit-msg: ./local_dev_tools/validate_commit_msg.dart
    pre-push: ./local_dev_tools/validate_branch.dart